# Generated by Django 5.2.3 on 2025-06-24 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('property_name', models.CharField(max_length=255, verbose_name='Объект')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(default='в работе', max_length=50, verbose_name='Статус')),
                ('commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Комиссия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Агент')),
            ],
        ),
    ]
